[profile.default]
solc = "0.8.0"
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
       "v3-core/=lib/v3-core/contracts/",
       "v3-periphery/=lib/v3-periphery/contracts/",
       "@openzeppelin/=lib/openzeppelin-contracts/"
   ]
optimizer = true
optimizer_runs = 200
# See more config options https://github.com/foundry-rs/foundry/tree/master/config